# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(869, 640)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_2.setStyleSheet("background:\n"
"rgb(38, 38, 38)")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_without_gas = QtWidgets.QPushButton(self.widget_2)
        self.button_without_gas.setStyleSheet("background:\n"
"rgb(255, 170, 0)")
        self.button_without_gas.setObjectName("button_without_gas")
        self.verticalLayout_2.addWidget(self.button_without_gas)
        self.button_difference = QtWidgets.QPushButton(self.widget_2)
        self.button_difference.setStyleSheet("background:\n"
"rgb(255, 170, 0)")
        self.button_difference.setObjectName("button_difference")
        self.verticalLayout_2.addWidget(self.button_difference)
        self.button_with_gas = QtWidgets.QPushButton(self.widget_2)
        self.button_with_gas.setStyleSheet("background:\n"
"rgb(255, 170, 0)")
        self.button_with_gas.setObjectName("button_with_gas")
        self.verticalLayout_2.addWidget(self.button_with_gas)
        self.button_the_most_high_gamma = QtWidgets.QPushButton(self.widget_2)
        self.button_the_most_high_gamma.setStyleSheet("background:\n"
"rgb(255, 170, 0)")
        self.button_the_most_high_gamma.setObjectName("button_the_most_high_gamma")
        self.verticalLayout_2.addWidget(self.button_the_most_high_gamma)
        self.line_procent = QtWidgets.QLineEdit(self.widget_2)
        self.line_procent.setStyleSheet("background:\n"
"rgb(255, 255, 255)\n"
"")
        self.line_procent.setObjectName("line_procent")
        self.verticalLayout_2.addWidget(self.line_procent)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background:\n"
"rgb(236, 236, 236)")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_plot_1 = QtWidgets.QWidget(self.widget)
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.layout_plot_1 = QtWidgets.QVBoxLayout(self.widget_plot_1)
        self.layout_plot_1.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_1.setSpacing(0)
        self.layout_plot_1.setObjectName("layout_plot_1")
        self.verticalLayout.addWidget(self.widget_plot_1)
        self.widget_plot_2 = QtWidgets.QWidget(self.widget)
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.layout_plot_2 = QtWidgets.QVBoxLayout(self.widget_plot_2)
        self.layout_plot_2.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_2.setSpacing(0)
        self.layout_plot_2.setObjectName("layout_plot_2")
        self.verticalLayout.addWidget(self.widget_plot_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_without_gas.setText(_translate("Dialog", "Без газа"))
        self.button_difference.setText(_translate("Dialog", "Отрисовать разницу"))
        self.button_with_gas.setText(_translate("Dialog", "C газом"))
        self.button_the_most_high_gamma.setText(_translate("Dialog", "Поиск гаммы выше порога"))
